name: Build, Push, and Run Docker Images

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-and-push-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image (testing)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.testing
          push: true
          tags: rigbytrash/gpstrackertesting:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          build-args:
            TAG_NAME=${{ github.ref_name == 'main' && 'latest' || github.ref_name }}

  run-testing-container:
    runs-on: ubuntu-latest
    needs: build-and-push-testing
    steps:
      - name: Run testing container
        run: |
          set -o pipefail
          docker pull rigbytrash/gpstrackertesting:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          docker run --rm rigbytrash/gpstrackertesting:${{ github.ref_name == 'main' && 'latest' || github.ref_name }} | tee output.txt
          if grep -qE "FAILED|FAIL:" output.txt; then
            echo "Test failed"
            exit 1
          else
            echo "Tests passed"
          fi
            
  build-and-push-app:
    runs-on: ubuntu-latest
    needs: run-testing-container
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image (app)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rigbytrash/gpstracker:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          build-args:
            TAG_NAME=${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
