name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: rhel-8

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.6.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: |
        export SQLALCHEMY_WARN_20=1
        export SQLALCHEMY_SILENCE_UBER_WARNING=1
        python -m unittest discover -s tests -p '*_test.py'
